### PR TITLE
Saving Google Images

### PR DESCRIPTION
**Pull request by wesfloyd**
38 of the images on our site point to files stored in a random googleimages domain. This is likely a holdover from github. This PR saves the images to our local repo and updates the image paths accordingly.

Question:
Should we save the script used for the image capture (under `/scripts`) for any future purposes? Or delete that file?

### CODE REVIEW

**Comment by wesfloyd** [comment]
Hi @shrimalmadhur and @QuinnLee would you have any time later this week to review this PR?

**Comment by shrimalmadhur** [comment]
I think we should save images like https://github.com/Layr-Labs/eigenlayer-docs/tree/main/static/img - like with proper folder and names. It's upfront some investment but it's cleaner and easy to navigate then one folder with images with random names.

**Review by shrimalmadhur — CHANGES_REQUESTED** [review]
I think we should save images like https://github.com/Layr-Labs/eigenlayer-docs/tree/main/static/img - like with proper folder and names. It's upfront some investment but it's cleaner and easy to navigate then one folder with images with random names.

**Comment by wesfloyd** [comment]
@shrimalmadhur good call and I agree. Do you mind if I create a linear ticket to track the additional effort to rename the images and their location?

For now I'm trying to avoid the risk where google stops hosting those images and our docs pages stop rendering the screenshot.

**Review by bpm6867 — APPROVED** [review]

**Review by shrimalmadhur — APPROVED** [review]

**Review by tinahaibodi — APPROVED** [review]

**Pull request merged**
