### PR TITLE
Fix air-gaped typo

### PR DESCRIPTION
**Pull request by marlowl**
**Description**
I was reading through the best practices for solo stakers and noticed what I believe to be a small typo.

### CODE REVIEW

**Comment by marlowl** [comment]
@dabit3 any update on this?

**Comment by dabit3** [comment]
Hi @marlowl thanks for the PR :) can you fix merge conflicts, then would be happy to merge

**Comment by marlowl** [comment]
@dabit3 merge conflict should be resolved!

**Comment by marlowl** [comment]
@dabit3 merge conflict should be resolved! 😄

**Review by dabit3 — APPROVED** [review]

**Comment by dabit3** [comment]
thank you @marlowl 🫡

**Pull request merged**
