### PR TITLE
fix: remove contract addresses from eigenlayer and eigenda pages in f…

### PR DESCRIPTION
**Pull request by wadealexc**
…avor of linking to github

* also renames both pages to make it clear what info can be found on the page

### CODE REVIEW

**Review by dabit3 — DISMISSED** [review]
LGTM

**Review by teddyknox — APPROVED** [review]
LGTM.

**Comment by wesfloyd** [comment]
Hi @wadealexc - the changes look great overall. Would you be open to keeping the existing page name "Deployed Contracts"? 


My concern is that the entire existing docs site is "Technical Docs" - eg its all technical documentation for EigenLayer. Whereas the "eigenlayer-contracts" repo contains equally technical documentation for the core EigenLayer solidity contracts and user flows.

Or if our goal is to raise awareness of the core contracts docs .. could we brainstorm another method that raises awareness with a more specific term (other than Technical Docs)? How about "Deployed Contracts and Docs" or similar?

And if we do need to change the page name - can we add [redirects](https://github.com/Layr-Labs/eigenlayer-docs/blob/0f8afd4df5d984e8c5cef091ea05449de8786144/docusaurus.config.js#L57) so that we don't break existing external links to the content? 

Thank you

**Comment by wadealexc** [comment]
Renamed to "Contract Addresses and Docs"

and added redirects

**Comment by wesfloyd** [comment]
latest changes lgtm

**Review by wesfloyd — APPROVED** [review]
lgtm

**Pull request merged**
